version: '3'

services:
  www:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/:/etc/nginx/conf.d
      - ./data/www/yacd:/www/nginx/html
      # - ./log/nginx:/var/log/nginx
    restart: unless-stopped
    networks:
      www:
  clash:
    image: chen_x/clash:alpine_armv8
    # privileged: true  # replaced by cap_add
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data/clash/:/clash
    networks:
      macnet:
    restart: unless-stopped
    entrypoint: ['/clash/entrypoint.sh']
networks:
  www:
  macnet:
    external: true
